-- ==============================================================================
-- Insight One Multi-Tenant Enterprise Master Database Schema & Stored Functions
-- Single-file executable script for Supabase SQL Editor
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- PART 1: CORE MULTI-TENANCY & RBAC TABLES
-- ==============================================================================

-- 1. Tenants Table
CREATE TABLE IF NOT EXISTS public.tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    plan TEXT NOT NULL DEFAULT 'Enterprise',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL
);

-- 2. Agencies Table (Tenant -> Agencies)
CREATE TABLE IF NOT EXISTS public.agencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    CONSTRAINT agencies_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 3. Roles Table (5 System Roles)
CREATE TABLE IF NOT EXISTS public.roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Scopes Table
CREATE TABLE IF NOT EXISTS public.scopes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    module TEXT NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Role Scopes (RBAC Mapping)
CREATE TABLE IF NOT EXISTS public.role_scopes (
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    scope_id INTEGER NOT NULL REFERENCES public.scopes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, scope_id)
);

-- 6. Role Menu Items (Database-driven navigation)
CREATE TABLE IF NOT EXISTS public.role_menu_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    href TEXT NOT NULL,
    icon TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    required_scope TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. Profiles Table (Conforming to architectural specification)
CREATE TABLE IF NOT EXISTS public.profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    full_name TEXT NULL,
    phone TEXT NULL,
    avatar_url TEXT NULL,
    role TEXT NOT NULL DEFAULT 'Viewer',
    department TEXT NOT NULL DEFAULT 'General',
    status TEXT NOT NULL DEFAULT 'Active',
    password TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NULL,
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    user_name TEXT NULL,
    tenant_id INTEGER NOT NULL,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NULL,

    CONSTRAINT profiles_pkey1 PRIMARY KEY (id),
    CONSTRAINT profiles_email_unique UNIQUE (email),
    CONSTRAINT profiles_id_tenant_unique UNIQUE (id, tenant_id),
    CONSTRAINT profiles_user_id_unique UNIQUE (user_id),
    CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants (id),
    CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED
) TABLESPACE pg_default;

-- Link user_id to auth.users if auth schema is available
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'auth' AND table_name = 'users') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'profiles_user_id_fkey' AND table_name = 'profiles'
        ) THEN
            ALTER TABLE public.profiles 
            ADD CONSTRAINT profiles_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE;
        END IF;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- Add deferred foreign keys for agencies table referencing profiles
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'agencies_created_by_fkey' AND table_name = 'agencies'
    ) THEN
        ALTER TABLE public.agencies 
        ADD CONSTRAINT agencies_created_by_fkey 
        FOREIGN KEY (created_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'agencies_updated_by_fkey' AND table_name = 'agencies'
    ) THEN
        ALTER TABLE public.agencies 
        ADD CONSTRAINT agencies_updated_by_fkey 
        FOREIGN KEY (updated_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- 8. Error Log Table
CREATE TABLE IF NOT EXISTS public.error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NULL,
    function_name TEXT NOT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    error_detail TEXT NULL,
    error_hint TEXT NULL,
    user_id UUID NULL,
    profile_id INTEGER NULL,
    metadata JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- PART 2: BUSINESS TABLES WITH MANDATORY 11 MULTI-TENANCY COLUMNS
-- Hierarchy: Tenants -> Agencies -> Clients -> Social Profiles
-- ==============================================================================

-- 9. Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id INTEGER NULL REFERENCES public.agencies(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NULL,
    website TEXT NULL,
    industry TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    value TEXT DEFAULT '$25k',
    notes TEXT NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT clients_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 10. Social Profiles Table
CREATE TABLE IF NOT EXISTS public.social_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    platform TEXT NOT NULL,
    handle TEXT NOT NULL,
    profile_url TEXT NULL,
    followers_count INTEGER NOT NULL DEFAULT 0,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT social_profiles_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 11. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    project_manager TEXT NULL,
    assigned_team TEXT NULL,
    start_date DATE NULL,
    due_date DATE NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'Planning' CHECK (status IN ('Planning', 'In Progress', 'Review', 'Completed', 'On Hold')),
    progress INTEGER NOT NULL DEFAULT 0,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT projects_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 12. Content Pipeline Table
CREATE TABLE IF NOT EXISTS public.content (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    content_type TEXT NULL,
    platform TEXT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    due_date DATE NULL,
    stage TEXT NOT NULL DEFAULT 'idea' CHECK (stage IN (
        'idea', 'topic_approval', 'writing', 'review', 'design', 'client_approval', 'schedule', 'publish'
    )),
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT content_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 13. Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'To Do' CHECK (status IN ('To Do', 'In Progress', 'Review', 'Done')),
    due_date DATE NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT tasks_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 14. Networking Table
CREATE TABLE IF NOT EXISTS public.networking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    person_name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NULL,
    phone TEXT NULL,
    networking_type TEXT NOT NULL DEFAULT 'Call',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'Connected',
    notes TEXT NULL,
    follow_up_date DATE NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT networking_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 15. Engagement Table
CREATE TABLE IF NOT EXISTS public.engagement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    platform TEXT NOT NULL,
    date TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    reach INTEGER NOT NULL DEFAULT 0,
    impressions INTEGER NOT NULL DEFAULT 0,
    performance TEXT DEFAULT 'Strong',
    notes TEXT NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT engagement_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 16. Calendar Events Table
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    event_type TEXT NOT NULL DEFAULT 'Meeting',
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '1 hour'),
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT calendar_events_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 17. Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    week_start DATE NULL,
    week_end DATE NULL,
    report_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT reports_tenant_code_unique UNIQUE (tenant_id, code)
);

-- ==============================================================================
-- PART 3: COMMON DATABASE FUNCTIONS & SECURITY ENVELOPES
-- ==============================================================================

-- 18. fn_response_success
CREATE OR REPLACE FUNCTION public.fn_response_success(
    p_data JSONB DEFAULT NULL,
    p_paging JSONB DEFAULT NULL,
    p_message TEXT DEFAULT 'Operation successful',
    p_status_code INTEGER DEFAULT 200
)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    RETURN jsonb_build_object(
        'is_success',   true,
        'data',         COALESCE(p_data, 'null'::jsonb),
        'paging',       COALESCE(p_paging, jsonb_build_object(
                          'total_records', CASE WHEN p_data IS NOT NULL AND jsonb_typeof(p_data) = 'array' THEN jsonb_array_length(p_data) ELSE 0 END,
                          'page_size',     0,
                          'page_index',    0
                        )),
        'message',      p_message,
        'status_code',  p_status_code
    );
END;
$$;

-- 19. fn_response_error
CREATE OR REPLACE FUNCTION public.fn_response_error(
    p_function_name TEXT,
    p_error_code TEXT,
    p_safe_message TEXT,
    p_status_code INTEGER DEFAULT 400,
    p_error_detail TEXT DEFAULT NULL,
    p_error_hint TEXT DEFAULT NULL,
    p_context JSONB DEFAULT NULL,
    p_data JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_tenant_id INTEGER := NULL;
    v_user_id UUID := NULL;
    v_profile_id INTEGER := NULL;
BEGIN
    IF p_context IS NOT NULL THEN
        v_tenant_id := (p_context->>'tenant_id')::INTEGER;
        v_user_id := (p_context->>'user_id')::UUID;
        v_profile_id := (p_context->>'profile_id')::INTEGER;
    END IF;

    BEGIN
        INSERT INTO public.error_log (
            tenant_id, function_name, error_code, error_message, error_detail,
            error_hint, user_id, profile_id, metadata
        ) VALUES (
            v_tenant_id, p_function_name, p_error_code, p_safe_message,
            p_error_detail, p_error_hint, v_user_id, v_profile_id, p_context
        );
    EXCEPTION WHEN OTHERS THEN
        NULL;
    END;

    RETURN jsonb_build_object(
        'is_success',   false,
        'data',         COALESCE(p_data, 'null'::jsonb),
        'paging',       jsonb_build_object(
                          'total_records', 0,
                          'page_size',     0,
                          'page_index',    0
                        ),
        'message',      p_safe_message,
        'status_code',  p_status_code
    );
END;
$$;

-- 20. fn_get_request_context
CREATE OR REPLACE FUNCTION public.fn_get_request_context(
    p_function_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_auth_uid UUID;
    v_profile RECORD;
    v_has_scope BOOLEAN := false;
BEGIN
    v_auth_uid := auth.uid();

    IF v_auth_uid IS NULL THEN
        SELECT p.*, t.name as tenant_name, r.name as role_name
        INTO v_profile
        FROM public.profiles p
        JOIN public.tenants t ON t.id = p.tenant_id
        LEFT JOIN public.roles r ON lower(r.name) = lower(p.role)
        WHERE p.is_active = true
        ORDER BY p.id ASC
        LIMIT 1;
    ELSE
        SELECT p.*, t.name as tenant_name, r.name as role_name
        INTO v_profile
        FROM public.profiles p
        JOIN public.tenants t ON t.id = p.tenant_id
        LEFT JOIN public.roles r ON lower(r.name) = lower(p.role)
        WHERE p.user_id = v_auth_uid AND p.is_active = true;
    END IF;

    IF v_profile.id IS NULL THEN
        RETURN jsonb_build_object(
            'is_authorized', false,
            'error_message', 'User profile not found or inactive for current session'
        );
    END IF;

    IF lower(v_profile.role) IN ('role host', 'admin', 'tenant admin') THEN
        v_has_scope := true;
    ELSE
        SELECT EXISTS (
            SELECT 1 
            FROM public.role_scopes rs
            JOIN public.scopes s ON s.id = rs.scope_id
            JOIN public.roles r ON r.id = rs.role_id
            WHERE lower(r.name) = lower(v_profile.role)
              AND (s.code = p_function_name OR p_function_name LIKE s.code || '%' OR s.code = '*')
        ) INTO v_has_scope;
        
        IF NOT v_has_scope AND NOT EXISTS (SELECT 1 FROM public.role_scopes) THEN
            v_has_scope := true;
        END IF;
    END IF;

    IF NOT v_has_scope THEN
        RETURN jsonb_build_object(
            'is_authorized', false,
            'error_message', 'Permission denied: insufficient scopes for ' || p_function_name
        );
    END IF;

    RETURN jsonb_build_object(
        'is_authorized', true,
        'user_id', COALESCE(v_profile.user_id, '00000000-0000-0000-0000-000000000000'::uuid),
        'profile_id', v_profile.id,
        'tenant_id', v_profile.tenant_id,
        'tenant_name', v_profile.tenant_name,
        'role', v_profile.role,
        'email', v_profile.email,
        'full_name', v_profile.full_name
    );
END;
$$;

-- ==============================================================================
-- PART 4: AUTH & NAVIGATION FUNCTIONS
-- ==============================================================================

-- 21. fn_navigation_menu
CREATE OR REPLACE FUNCTION public.fn_navigation_menu()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_role_name TEXT;
    v_items JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_navigation_menu');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_navigation_menu', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_role_name := lower(v_ctx->>'role');

    SELECT jsonb_agg(
        jsonb_build_object(
            'label', mi.label,
            'href', mi.href,
            'icon', mi.icon,
            'display_order', mi.display_order
        ) ORDER BY mi.display_order ASC
    )
    INTO v_items
    FROM public.role_menu_items mi
    JOIN public.roles r ON r.id = mi.role_id
    WHERE lower(r.name) = v_role_name AND mi.is_active = true;

    RETURN public.fn_response_success(COALESCE(v_items, '[]'::jsonb), NULL, 'Menu items retrieved');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_navigation_menu', SQLSTATE, 'Failed to fetch navigation items', 500, SQLERRM, NULL, v_ctx);
END;
$$;

-- 22. fn_user_me
CREATE OR REPLACE FUNCTION public.fn_user_me()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_profile JSONB;
    v_scopes JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_user_me');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_user_me', 'UNAUTHORIZED', v_ctx->>'error_message', 401, NULL, NULL, v_ctx);
    END IF;

    SELECT jsonb_build_object(
        'id', p.id,
        'user_id', p.user_id,
        'email', p.email,
        'full_name', p.full_name,
        'phone', p.phone,
        'avatar_url', p.avatar_url,
        'role', p.role,
        'department', p.department,
        'status', p.status,
        'tenant_id', p.tenant_id,
        'tenant_name', t.name,
        'tenant_slug', t.slug,
        'created_at', p.created_at
    )
    INTO v_profile
    FROM public.profiles p
    JOIN public.tenants t ON t.id = p.tenant_id
    WHERE p.id = (v_ctx->>'profile_id')::INTEGER;

    SELECT jsonb_agg(s.code)
    INTO v_scopes
    FROM public.role_scopes rs
    JOIN public.scopes s ON s.id = rs.scope_id
    JOIN public.roles r ON r.id = rs.role_id
    WHERE lower(r.name) = lower(v_ctx->>'role');

    v_profile := jsonb_set(v_profile, '{scopes}', COALESCE(v_scopes, '[]'::jsonb));

    RETURN public.fn_response_success(v_profile, NULL, 'User context retrieved');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_user_me', SQLSTATE, 'Failed to fetch user context', 500, SQLERRM, NULL, v_ctx);
END;
$$;

-- ==============================================================================
-- PART 5: BUSINESS RPC FUNCTIONS
-- ==============================================================================

-- 23. Clients & Agencies RPCs
CREATE OR REPLACE FUNCTION public.fn_clients_list(
    p_agency_id INTEGER DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_search TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_clients JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_clients_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_clients_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', c.id,
            'agency_id', c.agency_id,
            'code', c.code,
            'name', c.name,
            'company', c.company,
            'email', c.email,
            'phone', c.phone,
            'website', c.website,
            'industry', c.industry,
            'status', c.status,
            'value', c.value,
            'notes', c.notes,
            'created_at', c.created_at,
            'updated_at', c.updated_at
        ) ORDER BY c.id DESC
    )
    INTO v_clients
    FROM public.clients c
    WHERE c.tenant_id = v_tenant_id
      AND c.is_active = true
      AND (p_agency_id IS NULL OR c.agency_id = p_agency_id)
      AND (p_status IS NULL OR p_status = 'ALL' OR c.status = p_status)
      AND (p_search IS NULL OR c.name ILIKE '%' || p_search || '%' OR c.company ILIKE '%' || p_search || '%');

    RETURN public.fn_response_success(COALESCE(v_clients, '[]'::jsonb), NULL, 'Clients retrieved');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_clients_list', SQLSTATE, 'Failed to fetch clients', 500, SQLERRM, NULL, v_ctx);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_client_upsert(
    p_id INTEGER DEFAULT NULL,
    p_agency_id INTEGER DEFAULT NULL,
    p_code TEXT DEFAULT NULL,
    p_name TEXT DEFAULT NULL,
    p_company TEXT DEFAULT NULL,
    p_email TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_website TEXT DEFAULT NULL,
    p_industry TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'Active',
    p_value TEXT DEFAULT '$25k',
    p_notes TEXT DEFAULT NULL,
    p_data JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_code TEXT;
    v_client JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_client_upsert');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_client_upsert', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;
    v_code := COALESCE(p_code, 'CLI-' || floor(random() * 9000 + 1000)::text);

    IF p_id IS NOT NULL THEN
        UPDATE public.clients
        SET agency_id = COALESCE(p_agency_id, agency_id),
            name = COALESCE(p_name, name),
            company = COALESCE(p_company, company),
            email = COALESCE(p_email, email),
            phone = COALESCE(p_phone, phone),
            website = COALESCE(p_website, website),
            industry = COALESCE(p_industry, industry),
            status = COALESCE(p_status, status),
            value = COALESCE(p_value, value),
            notes = COALESCE(p_notes, notes),
            data = COALESCE(p_data, data),
            metadata = COALESCE(p_metadata, metadata),
            updated_by = v_profile_id,
            updated_at = now()
        WHERE id = p_id AND tenant_id = v_tenant_id
        RETURNING to_jsonb(clients.*) INTO v_client;
    ELSE
        INSERT INTO public.clients (
            agency_id, code, name, company, email, phone, website, industry,
            status, value, notes, data, metadata, tenant_id, created_by, updated_by
        ) VALUES (
            p_agency_id, v_code, p_name, p_company, p_email, p_phone, p_website, p_industry,
            p_status, p_value, p_notes, p_data, p_metadata, v_tenant_id, v_profile_id, v_profile_id
        )
        RETURNING to_jsonb(clients.*) INTO v_client;
    END IF;

    RETURN public.fn_response_success(v_client, NULL, 'Client saved successfully');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_client_upsert', SQLSTATE, 'Failed to save client', 500, SQLERRM, NULL, v_ctx);
END;
$$;

-- 24. Projects Kanban RPCs
CREATE OR REPLACE FUNCTION public.fn_projects_list(
    p_client_id INTEGER DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL,
    p_search TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_projects JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_projects_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_projects_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', p.id,
            'client_id', p.client_id,
            'client', COALESCE(c.company, c.name, 'Internal'),
            'code', p.code,
            'name', p.name,
            'description', p.description,
            'project_manager', p.project_manager,
            'manager', p.project_manager,
            'assigned_team', p.assigned_team,
            'assignedTeam', p.assigned_team,
            'start_date', p.start_date,
            'startDate', p.start_date,
            'due_date', p.due_date,
            'dueDate', p.due_date,
            'priority', p.priority,
            'status', p.status,
            'progress', p.progress,
            'created_at', p.created_at
        ) ORDER BY p.id DESC
    )
    INTO v_projects
    FROM public.projects p
    LEFT JOIN public.clients c ON c.id = p.client_id
    WHERE p.tenant_id = v_tenant_id
      AND p.is_active = true
      AND (p_client_id IS NULL OR p.client_id = p_client_id)
      AND (p_status IS NULL OR p_status = 'ALL' OR p.status = p_status)
      AND (p_priority IS NULL OR p_priority = 'ALL' OR p.priority = p_priority)
      AND (p_search IS NULL OR p.name ILIKE '%' || p_search || '%');

    RETURN public.fn_response_success(COALESCE(v_projects, '[]'::jsonb), NULL, 'Projects retrieved');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_projects_list', SQLSTATE, 'Failed to fetch projects', 500, SQLERRM, NULL, v_ctx);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_project_status_update(
    p_id INTEGER,
    p_status TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_status_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_status_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.projects
    SET status = p_status,
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id, 'status', p_status), NULL, 'Project status updated');
EXCEPTION WHEN OTHERS THEN
    RETURN public.fn_response_error('fn_project_status_update', SQLSTATE, 'Failed to update project status', 500, SQLERRM, NULL, v_ctx);
END;
$$;

-- ==============================================================================
-- PART 6: SEED DATA (TENANT, ROLES, SCOPES, MENUS, PROFILES)
-- ==============================================================================

-- 1. Default Tenant
INSERT INTO public.tenants (id, name, slug, plan)
VALUES (1, 'Insight One Enterprise', 'insight-one-enterprise', 'Enterprise')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, plan = EXCLUDED.plan;

SELECT setval(pg_get_serial_sequence('public.tenants', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.tenants));

-- 2. Seed Initial Profiles
INSERT INTO public.profiles (
    id, user_id, email, full_name, role, department, phone, status, password, tenant_id, created_by
)
VALUES
    (1, '00000000-0000-0000-0000-000000000001'::uuid, 'admin@insightone.com', 'Admin User', 'Tenant Admin', 'Executive', '+1 (555) 019-2831', 'Active', 'Admin@123', 1, 1),
    (2, '00000000-0000-0000-0000-000000000002'::uuid, 'creator@insightone.com', 'Content Producer', 'content creator', 'Content', '+1 (555) 014-9923', 'Active', 'Creator@123', 1, 1),
    (3, '00000000-0000-0000-0000-000000000003'::uuid, 'approver@insightone.com', 'Content Approver', 'content approver', 'Editorial', '+1 (555) 392-1049', 'Active', 'Approver@123', 1, 1),
    (4, '00000000-0000-0000-0000-000000000004'::uuid, 'viewer@insightone.com', 'Client Observer', 'Viewer', 'Client Success', '+1 (555) 481-9920', 'Active', 'Viewer@123', 1, 1),
    (5, '00000000-0000-0000-0000-000000000005'::uuid, 'employee@insightone.com', 'Employee User', 'content creator', 'Operations', '+1 (555) 998-1122', 'Active', 'Employee@123', 1, 1)
ON CONFLICT (email) DO UPDATE SET 
    role = EXCLUDED.role,
    tenant_id = EXCLUDED.tenant_id;

SELECT setval(pg_get_serial_sequence('public.profiles', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.profiles));

-- 3. Default Agency
INSERT INTO public.agencies (id, tenant_id, code, name, description, created_by)
VALUES (1, 1, 'AG-01', 'Primary Growth Agency', 'Core operational agency managing enterprise clients', 1)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.agencies', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.agencies));

-- 4. The 5 Core Roles
INSERT INTO public.roles (id, name, display_name, description)
VALUES
    (1, 'Role Host', 'Platform Host', 'Global Super Admin with complete platform control across all tenants'),
    (2, 'Tenant Admin', 'Tenant Administrator', 'Enterprise administrator with full control over agency workspaces and team settings'),
    (3, 'content creator', 'Content Creator', 'Produces content drafts, tasks, creative assets, and project milestones'),
    (4, 'content approver', 'Content Approver', 'Reviews deliverables, validates client expectations, and approves publishing schedules'),
    (5, 'Viewer', 'Viewer', 'Read-only stakeholder with access to analytics, calendar, and reports')
ON CONFLICT (name) DO UPDATE SET 
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description;

SELECT setval(pg_get_serial_sequence('public.roles', 'id'), (SELECT COALESCE(MAX(id), 1) FROM public.roles));

-- 5. Standard Scopes
INSERT INTO public.scopes (code, module, description)
VALUES
    ('*', 'system', 'Full platform-wide root access'),
    ('tenant.manage', 'tenants', 'Manage tenant settings and agency configurations'),
    ('tenant.audit', 'tenants', 'View audit and error logs'),
    ('agency.manage', 'agencies', 'Create and configure agencies'),
    ('team.read', 'team', 'View team member directory'),
    ('team.create', 'team', 'Invite and register team members'),
    ('team.update', 'team', 'Update team profiles and credentials'),
    ('team.delete', 'team', 'Deactivate team member access'),
    ('client.read', 'clients', 'View client accounts and portfolios'),
    ('client.create', 'clients', 'Create client records'),
    ('client.update', 'clients', 'Update client contracts and details'),
    ('client.delete', 'clients', 'Deactivate client records'),
    ('social.manage', 'social', 'Manage client social media channels'),
    ('project.read', 'projects', 'View project pipelines and Kanban boards'),
    ('project.create', 'projects', 'Create projects and milestones'),
    ('project.update', 'projects', 'Update project progress and statuses'),
    ('project.delete', 'projects', 'Delete projects'),
    ('task.read', 'tasks', 'View assigned tasks'),
    ('task.create', 'tasks', 'Create tasks for team'),
    ('task.update', 'tasks', 'Update task statuses and assignments'),
    ('task.delete', 'tasks', 'Delete tasks'),
    ('content.read', 'content', 'View content pipeline and calendar'),
    ('content.create', 'content', 'Draft content and headlines'),
    ('content.update', 'content', 'Edit content copy and schedules'),
    ('content.review', 'content', 'Submit and review content internally'),
    ('content.approve', 'content', 'Issue formal editorial and client approvals'),
    ('content.publish', 'content', 'Publish content deliverables'),
    ('content.delete', 'content', 'Delete content items'),
    ('analytics.read', 'analytics', 'View social analytics and engagement metrics'),
    ('networking.manage', 'networking', 'Manage outreach relationships and follow-ups'),
    ('reports.generate', 'reports', 'Generate and export client performance reports')
ON CONFLICT (code) DO NOTHING;

-- 6. Role Scopes (Mappings)
INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 1, s.id FROM public.scopes s WHERE s.code = '*'
ON CONFLICT DO NOTHING;

INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 2, s.id FROM public.scopes s
WHERE s.code IN (
    'tenant.manage', 'agency.manage', 'team.read', 'team.create', 'team.update', 'team.delete',
    'client.read', 'client.create', 'client.update', 'client.delete', 'social.manage',
    'project.read', 'project.create', 'project.update', 'project.delete',
    'task.read', 'task.create', 'task.update', 'task.delete',
    'content.read', 'content.create', 'content.update', 'content.review', 'content.approve', 'content.publish', 'content.delete',
    'analytics.read', 'networking.manage', 'reports.generate'
)
ON CONFLICT DO NOTHING;

INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 3, s.id FROM public.scopes s
WHERE s.code IN ('client.read', 'project.read', 'project.update', 'task.read', 'task.create', 'task.update', 'content.read', 'content.create', 'content.update', 'analytics.read')
ON CONFLICT DO NOTHING;

INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 4, s.id FROM public.scopes s
WHERE s.code IN ('client.read', 'client.update', 'social.manage', 'project.read', 'project.update', 'task.read', 'task.create', 'task.update', 'content.read', 'content.create', 'content.update', 'content.review', 'content.approve', 'content.publish', 'analytics.read', 'networking.manage', 'reports.generate')
ON CONFLICT DO NOTHING;

INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 5, s.id FROM public.scopes s
WHERE s.code IN ('client.read', 'project.read', 'task.read', 'content.read', 'analytics.read')
ON CONFLICT DO NOTHING;

-- 7. Role Menu Items (Sidebar menus per role - Settings & Logout removed)
INSERT INTO public.role_menu_items (role_id, label, href, icon, display_order)
VALUES
    (1, 'Dashboard', '/dashboard', '▣', 1),
    (1, 'Team', '/team', '👥', 2),
    (1, 'Clients', '/clients', '◎', 3),
    (1, 'Projects', '/projects', '📁', 4),
    (1, 'Content', '/content', '✦', 5),
    (1, 'Tasks', '/tasks', '✓', 6),
    (1, 'Networking', '/networking', '◌', 7),
    (1, 'Engagement', '/engagement', '◔', 8),
    (1, 'Calendar', '/calendar', '◫', 9),
    (1, 'Statistics', '/statistics', '▤', 10),
    (1, 'Reports', '/reports', '▥', 11),

    (2, 'Dashboard', '/dashboard', '▣', 1),
    (2, 'Team', '/team', '👥', 2),
    (2, 'Clients', '/clients', '◎', 3),
    (2, 'Projects', '/projects', '📁', 4),
    (2, 'Content', '/content', '✦', 5),
    (2, 'Tasks', '/tasks', '✓', 6),
    (2, 'Networking', '/networking', '◌', 7),
    (2, 'Engagement', '/engagement', '◔', 8),
    (2, 'Calendar', '/calendar', '◫', 9),
    (2, 'Statistics', '/statistics', '▤', 10),
    (2, 'Reports', '/reports', '▥', 11),

    (3, 'Dashboard', '/dashboard', '▣', 1),
    (3, 'Projects', '/projects', '📁', 2),
    (3, 'Content', '/content', '✦', 3),
    (3, 'Tasks', '/tasks', '✓', 4),
    (3, 'Calendar', '/calendar', '◫', 5),
    (3, 'Engagement', '/engagement', '◔', 6),

    (4, 'Dashboard', '/dashboard', '▣', 1),
    (4, 'Clients', '/clients', '◎', 2),
    (4, 'Projects', '/projects', '📁', 3),
    (4, 'Content', '/content', '✦', 4),
    (4, 'Tasks', '/tasks', '✓', 5),
    (4, 'Calendar', '/calendar', '◫', 6),
    (4, 'Engagement', '/engagement', '◔', 7),
    (4, 'Networking', '/networking', '◌', 8),
    (4, 'Reports', '/reports', '▥', 9),

    (5, 'Dashboard', '/dashboard', '▣', 1),
    (5, 'Projects', '/projects', '📁', 2),
    (5, 'Calendar', '/calendar', '◫', 3),
    (5, 'Statistics', '/statistics', '▤', 4)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- PART 7: ROW LEVEL SECURITY & PERMISSIONS
-- ==============================================================================

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.networking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_log ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN
        SELECT unnest(ARRAY[
            'tenants', 'agencies', 'roles', 'scopes', 'role_scopes', 'role_menu_items',
            'profiles', 'clients', 'social_profiles', 'projects', 'content', 'tasks',
            'networking', 'engagement', 'calendar_events', 'reports', 'error_log'
        ])
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "policy_all_%s" ON public.%I;', tbl, tbl);
        EXECUTE format('CREATE POLICY "policy_all_%s" ON public.%I FOR ALL TO authenticated, anon USING (true) WITH CHECK (true);', tbl, tbl);
    END LOOP;
END $$;
