-- ==============================================================================
-- Insight One Multi-Tenant Enterprise Architecture Schema & Database Functions
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- PART 1: CORE MULTI-TENANCY & RBAC TABLES
-- ==============================================================================

-- 1. Tenants Table
CREATE TABLE IF NOT EXISTS public.tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    plan TEXT NOT NULL DEFAULT 'Enterprise',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL
);

-- 2. Agencies Table (Tenant -> Agencies)
CREATE TABLE IF NOT EXISTS public.agencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL,
    CONSTRAINT agencies_tenant_name_unique UNIQUE (tenant_id, name)
);

-- 3. Roles Table
CREATE TABLE IF NOT EXISTS public.roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Scopes Table
CREATE TABLE IF NOT EXISTS public.scopes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    module TEXT NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Role Scopes (RBAC Mapping)
CREATE TABLE IF NOT EXISTS public.role_scopes (
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    scope_id INTEGER NOT NULL REFERENCES public.scopes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, scope_id)
);

-- 6. Role Menu Items (Database-driven navigation)
CREATE TABLE IF NOT EXISTS public.role_menu_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    href TEXT NOT NULL,
    icon TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    required_scope TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. Profiles Table (Conforming to architectural specification)
CREATE TABLE IF NOT EXISTS public.profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    full_name TEXT NULL,
    phone TEXT NULL,
    avatar_url TEXT NULL,
    role TEXT NOT NULL DEFAULT 'Employee',
    department TEXT NOT NULL DEFAULT 'General',
    status TEXT NOT NULL DEFAULT 'Active',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NULL,
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    user_name TEXT NULL,
    password TEXT NULL,
    tenant_id INTEGER NOT NULL,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NULL,

    CONSTRAINT profiles_pkey1 PRIMARY KEY (id),
    CONSTRAINT profiles_email_unique UNIQUE (email),
    CONSTRAINT profiles_id_tenant_unique UNIQUE (id, tenant_id),
    CONSTRAINT profiles_user_id_unique UNIQUE (user_id),
    CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants (id),
    CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED
);

-- Note: We link user_id to auth.users if auth.users exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'auth' AND table_name = 'users') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'profiles_user_id_fkey' AND table_name = 'profiles'
        ) THEN
            ALTER TABLE public.profiles 
            ADD CONSTRAINT profiles_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE;
        END IF;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- 8. Error Log Table (for safe technical error capture)
CREATE TABLE IF NOT EXISTS public.error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NULL,
    function_name TEXT NOT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    error_detail TEXT NULL,
    error_hint TEXT NULL,
    user_id UUID NULL,
    profile_id INTEGER NULL,
    metadata JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- PART 2: BUSINESS TABLES WITH REQUIRED COMMON COLUMNS
-- ==============================================================================
-- Common columns required on all business tables:
-- data jsonb null,
-- metadata jsonb null,
-- access_control jsonb null,
-- tenant_id integer not null references tenants(id),
-- is_active boolean not null default true,
-- created_by integer not null references profiles(id),
-- created_at timestamptz not null default now(),
-- updated_by integer null references profiles(id),
-- updated_at timestamptz not null default now()

-- 9. Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agency_id INTEGER NULL REFERENCES public.agencies(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NULL,
    website TEXT NULL,
    industry TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    notes TEXT NULL,
    value TEXT DEFAULT '$25k',
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 10. Social Profiles Table (Client -> Social Profiles)
CREATE TABLE IF NOT EXISTS public.social_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    handle TEXT NOT NULL,
    profile_url TEXT NULL,
    followers_count INTEGER NOT NULL DEFAULT 0,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 11. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NULL,
    project_manager TEXT NULL,
    assigned_team TEXT NULL,
    start_date DATE NULL,
    due_date DATE NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'Planning' CHECK (status IN ('Planning', 'In Progress', 'Review', 'Completed', 'On Hold')),
    progress INTEGER NOT NULL DEFAULT 0,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 12. Content Pipeline Table
CREATE TABLE IF NOT EXISTS public.content (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content_type TEXT NULL,
    platform TEXT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    due_date DATE NULL,
    stage TEXT NOT NULL DEFAULT 'idea' CHECK (stage IN (
        'idea',
        'topic_approval',
        'writing',
        'review',
        'design',
        'client_approval',
        'schedule',
        'publish'
    )),
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 13. Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'To Do' CHECK (status IN ('To Do', 'In Progress', 'Review', 'Done')),
    due_date DATE NULL,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 14. Networking Table
CREATE TABLE IF NOT EXISTS public.networking (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NULL,
    phone TEXT NULL,
    networking_type TEXT NOT NULL DEFAULT 'Call',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'Connected',
    notes TEXT NULL,
    follow_up_date DATE NULL,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 15. Engagement Table
CREATE TABLE IF NOT EXISTS public.engagement (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    date TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    reach INTEGER NOT NULL DEFAULT 0,
    impressions INTEGER NOT NULL DEFAULT 0,
    performance TEXT DEFAULT 'Strong',
    notes TEXT NULL,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 16. Calendar Events Table
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    event_type TEXT NOT NULL DEFAULT 'Meeting',
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '1 hour'),
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 17. Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
    week_start DATE NULL,
    week_end DATE NULL,
    report_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    
    -- Common columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==============================================================================
-- PART 3: COMMON DATABASE FUNCTIONS
-- ==============================================================================

-- 18. fn_response_success
CREATE OR REPLACE FUNCTION public.fn_response_success(
    p_data JSONB DEFAULT NULL,
    p_paging JSONB DEFAULT NULL,
    p_message TEXT DEFAULT 'Operation successful',
    p_status_code INTEGER DEFAULT 200
)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    RETURN jsonb_build_object(
        'is_success', true,
        'data', COALESCE(p_data, 'null'::jsonb),
        'paging', COALESCE(p_paging, jsonb_build_object(
            'total_records', CASE WHEN p_data IS NOT NULL AND jsonb_typeof(p_data) = 'array' THEN jsonb_array_length(p_data) ELSE 0 END,
            'page_size', 0,
            'page_index', 0
        )),
        'message', p_message,
        'status_code', p_status_code
    );
END;
$$;

-- 19. fn_response_error
CREATE OR REPLACE FUNCTION public.fn_response_error(
    p_function_name TEXT,
    p_error_code TEXT,
    p_safe_message TEXT,
    p_status_code INTEGER DEFAULT 400,
    p_error_detail TEXT DEFAULT NULL,
    p_error_hint TEXT DEFAULT NULL,
    p_context JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_tenant_id INTEGER := NULL;
    v_user_id UUID := NULL;
    v_profile_id INTEGER := NULL;
BEGIN
    -- Extract context identifiers if provided
    IF p_context IS NOT NULL THEN
        v_tenant_id := (p_context->>'tenant_id')::INTEGER;
        v_user_id := (p_context->>'user_id')::UUID;
        v_profile_id := (p_context->>'profile_id')::INTEGER;
    END IF;

    -- Safely log technical error
    BEGIN
        INSERT INTO public.error_log (
            tenant_id,
            function_name,
            error_code,
            error_message,
            error_detail,
            error_hint,
            user_id,
            profile_id,
            metadata
        ) VALUES (
            v_tenant_id,
            p_function_name,
            p_error_code,
            p_safe_message,
            p_error_detail,
            p_error_hint,
            v_user_id,
            v_profile_id,
            p_context
        );
    EXCEPTION WHEN OTHERS THEN
        -- Never fail if error logging encounters an issue
        NULL;
    END;

    -- Return safe user-facing JSONB response
    RETURN jsonb_build_object(
        'is_success', false,
        'data', 'null'::jsonb,
        'paging', jsonb_build_object(
            'total_records', 0,
            'page_size', 0,
            'page_index', 0
        ),
        'message', p_safe_message,
        'status_code', p_status_code
    );
END;
$$;

-- 20. fn_get_request_context
CREATE OR REPLACE FUNCTION public.fn_get_request_context(
    p_function_name TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_auth_uid UUID;
    v_profile RECORD;
    v_has_scope BOOLEAN := false;
BEGIN
    -- 1. Identify authenticated Supabase user
    v_auth_uid := auth.uid();

    -- Fallback for development/demo: if no auth session, find first active admin profile
    IF v_auth_uid IS NULL THEN
        SELECT p.*, t.name as tenant_name, r.name as role_name
        INTO v_profile
        FROM public.profiles p
        JOIN public.tenants t ON t.id = p.tenant_id
        LEFT JOIN public.roles r ON lower(r.name) = lower(p.role)
        WHERE p.is_active = true
        ORDER BY p.id ASC
        LIMIT 1;
    ELSE
        SELECT p.*, t.name as tenant_name, r.name as role_name
        INTO v_profile
        FROM public.profiles p
        JOIN public.tenants t ON t.id = p.tenant_id
        LEFT JOIN public.roles r ON lower(r.name) = lower(p.role)
        WHERE p.user_id = v_auth_uid AND p.is_active = true;
    END IF;

    -- If no profile found, raise unauthorized
    IF v_profile.id IS NULL THEN
        RETURN jsonb_build_object(
            'is_authorized', false,
            'error_message', 'User profile not found or inactive for current session'
        );
    END IF;

    -- 2. Validate scope / function permission if role scopes are configured
    IF lower(v_profile.role) = 'admin' THEN
        v_has_scope := true;
    ELSE
        -- Check if role has scope matching the function or wildcard
        SELECT EXISTS (
            SELECT 1 
            FROM public.role_scopes rs
            JOIN public.scopes s ON s.id = rs.scope_id
            JOIN public.roles r ON r.id = rs.role_id
            WHERE lower(r.name) = lower(v_profile.role)
              AND (
                  s.code = p_function_name 
                  OR p_function_name LIKE s.code || '%'
                  OR s.code = '*'
              )
        ) INTO v_has_scope;
        
        -- If no explicit role scope mapping defined yet, default allow for employee on read/standard operations
        IF NOT v_has_scope AND NOT EXISTS (SELECT 1 FROM public.role_scopes) THEN
            v_has_scope := true;
        END IF;
    END IF;

    IF NOT v_has_scope THEN
        RETURN jsonb_build_object(
            'is_authorized', false,
            'error_message', 'Permission denied: insufficient scopes for ' || p_function_name
        );
    END IF;

    -- Return valid context
    RETURN jsonb_build_object(
        'is_authorized', true,
        'user_id', COALESCE(v_profile.user_id, '00000000-0000-0000-0000-000000000000'::uuid),
        'profile_id', v_profile.id,
        'tenant_id', v_profile.tenant_id,
        'tenant_name', v_profile.tenant_name,
        'role', v_profile.role,
        'email', v_profile.email,
        'full_name', v_profile.full_name
    );
END;
$$;

-- ==============================================================================
-- PART 4: BUSINESS RPC FUNCTIONS (JSONB RETURN, P_ PARAMS, SECURITY DEFINER)
-- ==============================================================================

-- 21. fn_navigation_menu (Database-driven sidebar)
CREATE OR REPLACE FUNCTION public.fn_navigation_menu()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_role_name TEXT;
    v_items JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_navigation_menu');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_navigation_menu', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_role_name := lower(v_ctx->>'role');

    SELECT jsonb_agg(
        jsonb_build_object(
            'label', mi.label,
            'href', mi.href,
            'icon', mi.icon,
            'display_order', mi.display_order
        ) ORDER BY mi.display_order ASC
    )
    INTO v_items
    FROM public.role_menu_items mi
    JOIN public.roles r ON r.id = mi.role_id
    WHERE lower(r.name) = v_role_name AND mi.is_active = true;

    RETURN public.fn_response_success(COALESCE(v_items, '[]'::jsonb), NULL, 'Menu items retrieved');
END;
$$;

-- 22. fn_user_me (Current authenticated profile & tenant context)
CREATE OR REPLACE FUNCTION public.fn_user_me()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_profile JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_user_me');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_user_me', 'UNAUTHORIZED', v_ctx->>'error_message', 401, NULL, NULL, v_ctx);
    END IF;

    SELECT jsonb_build_object(
        'id', p.id,
        'user_id', p.user_id,
        'email', p.email,
        'full_name', p.full_name,
        'role', p.role,
        'department', p.department,
        'phone', p.phone,
        'avatar_url', p.avatar_url,
        'tenant_id', p.tenant_id,
        'tenant_name', t.name
    )
    INTO v_profile
    FROM public.profiles p
    JOIN public.tenants t ON t.id = p.tenant_id
    WHERE p.id = (v_ctx->>'profile_id')::INTEGER;

    RETURN public.fn_response_success(v_profile, NULL, 'Current user context');
END;
$$;

-- ------------------------------------------------------------------------------
-- CLIENT RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_client_list(
    p_search TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_client_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_client_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', c.id,
            'name', c.name,
            'company', c.company,
            'email', c.email,
            'phone', c.phone,
            'website', c.website,
            'industry', c.industry,
            'status', c.status,
            'value', c.value,
            'notes', c.notes,
            'tenant_id', c.tenant_id,
            'created_at', c.created_at,
            'updated_at', c.updated_at
        ) ORDER BY c.created_at DESC
    )
    INTO v_data
    FROM public.clients c
    WHERE c.tenant_id = v_tenant_id
      AND c.is_active = true
      AND (p_status IS NULL OR p_status = 'ALL' OR c.status = p_status)
      AND (
          p_search IS NULL OR p_search = '' 
          OR c.name ILIKE '%' || p_search || '%'
          OR c.company ILIKE '%' || p_search || '%'
          OR c.email ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Clients retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_client_create(
    p_name TEXT,
    p_company TEXT,
    p_email TEXT,
    p_phone TEXT DEFAULT NULL,
    p_website TEXT DEFAULT NULL,
    p_industry TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'Active',
    p_value TEXT DEFAULT '$25k',
    p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_client JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_client_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_client_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.clients (
        name,
        company,
        email,
        phone,
        website,
        industry,
        status,
        value,
        notes,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_name,
        p_company,
        p_email,
        p_phone,
        p_website,
        p_industry,
        p_status,
        p_value,
        p_notes,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'company', c.company,
        'email', c.email,
        'phone', c.phone,
        'website', c.website,
        'industry', c.industry,
        'status', c.status,
        'value', c.value,
        'notes', c.notes,
        'tenant_id', c.tenant_id,
        'created_at', c.created_at
    ) INTO v_client
    FROM public.clients c
    WHERE c.id = v_new_id;

    RETURN public.fn_response_success(v_client, NULL, 'Client created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_client_update(
    p_id UUID,
    p_name TEXT DEFAULT NULL,
    p_company TEXT DEFAULT NULL,
    p_email TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_website TEXT DEFAULT NULL,
    p_industry TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_value TEXT DEFAULT NULL,
    p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_client JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_client_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_client_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.clients
    SET
        name = COALESCE(p_name, name),
        company = COALESCE(p_company, company),
        email = COALESCE(p_email, email),
        phone = COALESCE(p_phone, phone),
        website = COALESCE(p_website, website),
        industry = COALESCE(p_industry, industry),
        status = COALESCE(p_status, status),
        value = COALESCE(p_value, value),
        notes = COALESCE(p_notes, notes),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'company', c.company,
        'email', c.email,
        'phone', c.phone,
        'website', c.website,
        'industry', c.industry,
        'status', c.status,
        'value', c.value,
        'notes', c.notes,
        'updated_at', c.updated_at
    ) INTO v_client
    FROM public.clients c
    WHERE c.id = p_id;

    RETURN public.fn_response_success(v_client, NULL, 'Client updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_client_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_client_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_client_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.clients
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Client deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- PROJECT RPC FUNCTIONS (KANBAN & CRUD)
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_project_list(
    p_search TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', p.id,
            'name', p.name,
            'client_id', p.client_id,
            'client', COALESCE(c.company, c.name, 'Internal Project'),
            'description', p.description,
            'manager', p.project_manager,
            'project_manager', p.project_manager,
            'assignedTeam', p.assigned_team,
            'assigned_team', p.assigned_team,
            'startDate', p.start_date,
            'start_date', p.start_date,
            'dueDate', p.due_date,
            'due_date', p.due_date,
            'priority', p.priority,
            'status', p.status,
            'progress', p.progress,
            'tenant_id', p.tenant_id,
            'created_at', p.created_at,
            'updated_at', p.updated_at
        ) ORDER BY p.created_at DESC
    )
    INTO v_data
    FROM public.projects p
    LEFT JOIN public.clients c ON c.id = p.client_id
    WHERE p.tenant_id = v_tenant_id
      AND p.is_active = true
      AND (p_status IS NULL OR p_status = 'ALL' OR p.status = p_status)
      AND (p_priority IS NULL OR p_priority = 'ALL' OR p.priority = p_priority)
      AND (
          p_search IS NULL OR p_search = ''
          OR p.name ILIKE '%' || p_search || '%'
          OR p.project_manager ILIKE '%' || p_search || '%'
          OR COALESCE(c.company, '') ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Projects retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_project_create(
    p_name TEXT,
    p_client_id UUID DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_project_manager TEXT DEFAULT NULL,
    p_assigned_team TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_due_date DATE DEFAULT NULL,
    p_priority TEXT DEFAULT 'Medium',
    p_status TEXT DEFAULT 'Planning',
    p_progress INTEGER DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_project JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.projects (
        name,
        client_id,
        description,
        project_manager,
        assigned_team,
        start_date,
        due_date,
        priority,
        status,
        progress,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_name,
        p_client_id,
        p_description,
        p_project_manager,
        p_assigned_team,
        p_start_date,
        p_due_date,
        p_priority,
        p_status,
        p_progress,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', p.id,
        'name', p.name,
        'client_id', p.client_id,
        'client', COALESCE(c.company, c.name, 'Internal Project'),
        'description', p.description,
        'manager', p.project_manager,
        'assignedTeam', p.assigned_team,
        'startDate', p.start_date,
        'dueDate', p.due_date,
        'priority', p.priority,
        'status', p.status,
        'progress', p.progress,
        'created_at', p.created_at
    ) INTO v_project
    FROM public.projects p
    LEFT JOIN public.clients c ON c.id = p.client_id
    WHERE p.id = v_new_id;

    RETURN public.fn_response_success(v_project, NULL, 'Project created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_project_status_update(
    p_id UUID,
    p_status TEXT,
    p_progress INTEGER DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_status_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_status_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.projects
    SET
        status = p_status,
        progress = COALESCE(p_progress, CASE WHEN p_status = 'Completed' THEN 100 ELSE progress END),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id, 'status', p_status), NULL, 'Project status updated');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_project_update(
    p_id UUID,
    p_name TEXT DEFAULT NULL,
    p_client_id UUID DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_project_manager TEXT DEFAULT NULL,
    p_assigned_team TEXT DEFAULT NULL,
    p_start_date DATE DEFAULT NULL,
    p_due_date DATE DEFAULT NULL,
    p_priority TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_progress INTEGER DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_project JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.projects
    SET
        name = COALESCE(p_name, name),
        client_id = COALESCE(p_client_id, client_id),
        description = COALESCE(p_description, description),
        project_manager = COALESCE(p_project_manager, project_manager),
        assigned_team = COALESCE(p_assigned_team, assigned_team),
        start_date = COALESCE(p_start_date, start_date),
        due_date = COALESCE(p_due_date, due_date),
        priority = COALESCE(p_priority, priority),
        status = COALESCE(p_status, status),
        progress = COALESCE(p_progress, progress),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', p.id,
        'name', p.name,
        'client_id', p.client_id,
        'client', COALESCE(c.company, c.name, 'Internal Project'),
        'description', p.description,
        'manager', p.project_manager,
        'assignedTeam', p.assigned_team,
        'startDate', p.start_date,
        'dueDate', p.due_date,
        'priority', p.priority,
        'status', p.status,
        'progress', p.progress,
        'updated_at', p.updated_at
    ) INTO v_project
    FROM public.projects p
    LEFT JOIN public.clients c ON c.id = p.client_id
    WHERE p.id = p_id;

    RETURN public.fn_response_success(v_project, NULL, 'Project updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_project_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_project_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_project_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.projects
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Project deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- TASK RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_task_list(
    p_search TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_task_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_task_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', t.id,
            'title', t.title,
            'description', t.description,
            'client_id', t.client_id,
            'client', COALESCE(c.company, c.name, 'Internal Task'),
            'assignee', t.assigned_employee,
            'assigned_employee', t.assigned_employee,
            'priority', t.priority,
            'status', t.status,
            'dueDate', t.due_date,
            'due_date', t.due_date,
            'tenant_id', t.tenant_id,
            'created_at', t.created_at
        ) ORDER BY t.created_at DESC
    )
    INTO v_data
    FROM public.tasks t
    LEFT JOIN public.clients c ON c.id = t.client_id
    WHERE t.tenant_id = v_tenant_id
      AND t.is_active = true
      AND (p_status IS NULL OR p_status = 'ALL' OR t.status = p_status)
      AND (p_priority IS NULL OR p_priority = 'ALL' OR t.priority = p_priority)
      AND (
          p_search IS NULL OR p_search = ''
          OR t.title ILIKE '%' || p_search || '%'
          OR t.assigned_employee ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Tasks retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_task_create(
    p_title TEXT,
    p_client_id UUID DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_assigned_employee TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT 'Medium',
    p_status TEXT DEFAULT 'To Do',
    p_due_date DATE DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_task JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_task_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_task_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.tasks (
        title,
        client_id,
        description,
        assigned_employee,
        priority,
        status,
        due_date,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_title,
        p_client_id,
        p_description,
        p_assigned_employee,
        p_priority,
        p_status,
        p_due_date,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', t.id,
        'title', t.title,
        'client_id', t.client_id,
        'description', t.description,
        'assignee', t.assigned_employee,
        'priority', t.priority,
        'status', t.status,
        'dueDate', t.due_date,
        'created_at', t.created_at
    ) INTO v_task
    FROM public.tasks t
    WHERE t.id = v_new_id;

    RETURN public.fn_response_success(v_task, NULL, 'Task created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_task_update(
    p_id UUID,
    p_title TEXT DEFAULT NULL,
    p_client_id UUID DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_assigned_employee TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_due_date DATE DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_task JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_task_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_task_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.tasks
    SET
        title = COALESCE(p_title, title),
        client_id = COALESCE(p_client_id, client_id),
        description = COALESCE(p_description, description),
        assigned_employee = COALESCE(p_assigned_employee, assigned_employee),
        priority = COALESCE(p_priority, priority),
        status = COALESCE(p_status, status),
        due_date = COALESCE(p_due_date, due_date),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', t.id,
        'title', t.title,
        'client_id', t.client_id,
        'description', t.description,
        'assignee', t.assigned_employee,
        'priority', t.priority,
        'status', t.status,
        'dueDate', t.due_date,
        'updated_at', t.updated_at
    ) INTO v_task
    FROM public.tasks t
    WHERE t.id = p_id;

    RETURN public.fn_response_success(v_task, NULL, 'Task updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_task_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_task_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_task_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.tasks
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Task deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- TEAM / PROFILE RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_team_list(
    p_search TEXT DEFAULT NULL,
    p_department TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_team_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_team_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', p.id,
            'name', COALESCE(p.full_name, p.email),
            'full_name', p.full_name,
            'email', p.email,
            'role', p.role,
            'department', p.department,
            'phone', p.phone,
            'status', p.status,
            'tenant_id', p.tenant_id,
            'created_at', p.created_at
        ) ORDER BY p.created_at DESC
    )
    INTO v_data
    FROM public.profiles p
    WHERE p.tenant_id = v_tenant_id
      AND p.is_active = true
      AND (p_department IS NULL OR p_department = 'ALL' OR p.department = p_department)
      AND (p_status IS NULL OR p_status = 'ALL' OR p.status = p_status)
      AND (
          p_search IS NULL OR p_search = ''
          OR p.full_name ILIKE '%' || p_search || '%'
          OR p.email ILIKE '%' || p_search || '%'
          OR p.role ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Team members retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_team_create(
    p_name TEXT,
    p_email TEXT,
    p_role TEXT,
    p_department TEXT DEFAULT 'General',
    p_phone TEXT DEFAULT NULL,
    p_status TEXT DEFAULT 'Active',
    p_password TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id INTEGER;
    v_fake_user_id UUID := gen_random_uuid();
    v_member JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_team_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_team_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.profiles (
        user_id,
        email,
        full_name,
        role,
        department,
        phone,
        status,
        password,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        v_fake_user_id,
        lower(p_email),
        p_name,
        p_role,
        p_department,
        p_phone,
        p_status,
        p_password,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', p.id,
        'name', p.full_name,
        'email', p.email,
        'role', p.role,
        'department', p.department,
        'phone', p.phone,
        'status', p.status,
        'created_at', p.created_at
    ) INTO v_member
    FROM public.profiles p
    WHERE p.id = v_new_id;

    RETURN public.fn_response_success(v_member, NULL, 'Team member created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_team_update(
    p_id INTEGER,
    p_name TEXT DEFAULT NULL,
    p_email TEXT DEFAULT NULL,
    p_role TEXT DEFAULT NULL,
    p_department TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_password TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_member JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_team_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_team_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.profiles
    SET
        full_name = COALESCE(p_name, full_name),
        email = COALESCE(lower(p_email), email),
        role = COALESCE(p_role, role),
        department = COALESCE(p_department, department),
        phone = COALESCE(p_phone, phone),
        status = COALESCE(p_status, status),
        password = CASE WHEN p_password IS NOT NULL AND p_password <> '' THEN p_password ELSE password END,
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', p.id,
        'name', p.full_name,
        'email', p.email,
        'role', p.role,
        'department', p.department,
        'phone', p.phone,
        'status', p.status,
        'updated_at', p.updated_at
    ) INTO v_member
    FROM public.profiles p
    WHERE p.id = p_id;

    RETURN public.fn_response_success(v_member, NULL, 'Team member updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_team_delete(
    p_id INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_team_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_team_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.profiles
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Team member deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- CONTENT PIPELINE RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_content_list(
    p_search TEXT DEFAULT NULL,
    p_stage TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_content_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_content_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', ct.id,
            'client_id', ct.client_id,
            'client', COALESCE(c.company, c.name, 'Internal'),
            'title', ct.title,
            'contentType', ct.content_type,
            'platform', ct.platform,
            'description', ct.description,
            'assignee', ct.assigned_employee,
            'priority', ct.priority,
            'dueDate', ct.due_date,
            'status', ct.stage,
            'stage', ct.stage,
            'tenant_id', ct.tenant_id,
            'created_at', ct.created_at
        ) ORDER BY ct.created_at DESC
    )
    INTO v_data
    FROM public.content ct
    LEFT JOIN public.clients c ON c.id = ct.client_id
    WHERE ct.tenant_id = v_tenant_id
      AND ct.is_active = true
      AND (p_stage IS NULL OR p_stage = 'ALL' OR ct.stage = lower(p_stage))
      AND (p_priority IS NULL OR p_priority = 'ALL' OR ct.priority = p_priority)
      AND (
          p_search IS NULL OR p_search = ''
          OR ct.title ILIKE '%' || p_search || '%'
          OR ct.platform ILIKE '%' || p_search || '%'
          OR ct.assigned_employee ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Content pipeline retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_content_create(
    p_title TEXT,
    p_client_id UUID DEFAULT NULL,
    p_content_type TEXT DEFAULT NULL,
    p_platform TEXT DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_assigned_employee TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT 'Medium',
    p_due_date DATE DEFAULT NULL,
    p_stage TEXT DEFAULT 'idea'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_content JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_content_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_content_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.content (
        title,
        client_id,
        content_type,
        platform,
        description,
        assigned_employee,
        priority,
        due_date,
        stage,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_title,
        p_client_id,
        p_content_type,
        p_platform,
        p_description,
        p_assigned_employee,
        p_priority,
        p_due_date,
        lower(p_stage),
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', ct.id,
        'title', ct.title,
        'client_id', ct.client_id,
        'contentType', ct.content_type,
        'platform', ct.platform,
        'description', ct.description,
        'assignee', ct.assigned_employee,
        'priority', ct.priority,
        'dueDate', ct.due_date,
        'status', ct.stage,
        'created_at', ct.created_at
    ) INTO v_content
    FROM public.content ct
    WHERE ct.id = v_new_id;

    RETURN public.fn_response_success(v_content, NULL, 'Content created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_content_update(
    p_id UUID,
    p_title TEXT DEFAULT NULL,
    p_client_id UUID DEFAULT NULL,
    p_content_type TEXT DEFAULT NULL,
    p_platform TEXT DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_assigned_employee TEXT DEFAULT NULL,
    p_priority TEXT DEFAULT NULL,
    p_due_date DATE DEFAULT NULL,
    p_stage TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_content JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_content_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_content_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.content
    SET
        title = COALESCE(p_title, title),
        client_id = COALESCE(p_client_id, client_id),
        content_type = COALESCE(p_content_type, content_type),
        platform = COALESCE(p_platform, platform),
        description = COALESCE(p_description, description),
        assigned_employee = COALESCE(p_assigned_employee, assigned_employee),
        priority = COALESCE(p_priority, priority),
        due_date = COALESCE(p_due_date, due_date),
        stage = COALESCE(lower(p_stage), stage),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', ct.id,
        'title', ct.title,
        'client_id', ct.client_id,
        'contentType', ct.content_type,
        'platform', ct.platform,
        'description', ct.description,
        'assignee', ct.assigned_employee,
        'priority', ct.priority,
        'dueDate', ct.due_date,
        'status', ct.stage,
        'updated_at', ct.updated_at
    ) INTO v_content
    FROM public.content ct
    WHERE ct.id = p_id;

    RETURN public.fn_response_success(v_content, NULL, 'Content updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_content_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_content_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_content_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.content
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Content deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- NETWORKING RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_networking_list(
    p_search TEXT DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_type TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_networking_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_networking_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', n.id,
            'person', n.person_name,
            'company', n.company,
            'email', n.email,
            'phone', n.phone,
            'date', n.date,
            'type', n.networking_type,
            'status', n.status,
            'notes', n.notes,
            'followUpDate', n.follow_up_date,
            'tenant_id', n.tenant_id,
            'created_at', n.created_at
        ) ORDER BY n.created_at DESC
    )
    INTO v_data
    FROM public.networking n
    WHERE n.tenant_id = v_tenant_id
      AND n.is_active = true
      AND (p_status IS NULL OR p_status = 'ALL' OR n.status = p_status)
      AND (p_type IS NULL OR p_type = 'ALL' OR n.networking_type = p_type)
      AND (
          p_search IS NULL OR p_search = ''
          OR n.person_name ILIKE '%' || p_search || '%'
          OR n.company ILIKE '%' || p_search || '%'
          OR n.email ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Networking contacts retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_networking_create(
    p_person_name TEXT,
    p_company TEXT,
    p_email TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_networking_type TEXT DEFAULT 'Call',
    p_date DATE DEFAULT CURRENT_DATE,
    p_status TEXT DEFAULT 'Connected',
    p_notes TEXT DEFAULT NULL,
    p_follow_up_date DATE DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_contact JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_networking_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_networking_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.networking (
        person_name,
        company,
        email,
        phone,
        networking_type,
        date,
        status,
        notes,
        follow_up_date,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_person_name,
        p_company,
        p_email,
        p_phone,
        p_networking_type,
        p_date,
        p_status,
        p_notes,
        p_follow_up_date,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', n.id,
        'person', n.person_name,
        'company', n.company,
        'email', n.email,
        'phone', n.phone,
        'date', n.date,
        'type', n.networking_type,
        'status', n.status,
        'notes', n.notes,
        'followUpDate', n.follow_up_date,
        'created_at', n.created_at
    ) INTO v_contact
    FROM public.networking n
    WHERE n.id = v_new_id;

    RETURN public.fn_response_success(v_contact, NULL, 'Networking entry created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_networking_update(
    p_id UUID,
    p_person_name TEXT DEFAULT NULL,
    p_company TEXT DEFAULT NULL,
    p_email TEXT DEFAULT NULL,
    p_phone TEXT DEFAULT NULL,
    p_networking_type TEXT DEFAULT NULL,
    p_date DATE DEFAULT NULL,
    p_status TEXT DEFAULT NULL,
    p_notes TEXT DEFAULT NULL,
    p_follow_up_date DATE DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_contact JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_networking_update');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_networking_update', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    UPDATE public.networking
    SET
        person_name = COALESCE(p_person_name, person_name),
        company = COALESCE(p_company, company),
        email = COALESCE(p_email, email),
        phone = COALESCE(p_phone, phone),
        networking_type = COALESCE(p_networking_type, networking_type),
        date = COALESCE(p_date, date),
        status = COALESCE(p_status, status),
        notes = COALESCE(p_notes, notes),
        follow_up_date = COALESCE(p_follow_up_date, follow_up_date),
        updated_by = v_profile_id,
        updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id AND is_active = true;

    SELECT jsonb_build_object(
        'id', n.id,
        'person', n.person_name,
        'company', n.company,
        'email', n.email,
        'phone', n.phone,
        'date', n.date,
        'type', n.networking_type,
        'status', n.status,
        'notes', n.notes,
        'followUpDate', n.follow_up_date,
        'updated_at', n.updated_at
    ) INTO v_contact
    FROM public.networking n
    WHERE n.id = p_id;

    RETURN public.fn_response_success(v_contact, NULL, 'Networking entry updated successfully');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_networking_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_networking_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_networking_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.networking
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Networking entry deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- CALENDAR RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_calendar_event_list(
    p_search TEXT DEFAULT NULL,
    p_type TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_calendar_event_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_calendar_event_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', e.id,
            'title', e.title,
            'description', e.description,
            'client_id', e.client_id,
            'client', COALESCE(c.company, c.name, 'Internal'),
            'type', e.event_type,
            'startTime', e.start_time,
            'endTime', e.end_time,
            'date', to_char(e.start_time, 'YYYY-MM-DD'),
            'tenant_id', e.tenant_id,
            'created_at', e.created_at
        ) ORDER BY e.start_time ASC
    )
    INTO v_data
    FROM public.calendar_events e
    LEFT JOIN public.clients c ON c.id = e.client_id
    WHERE e.tenant_id = v_tenant_id
      AND e.is_active = true
      AND (p_type IS NULL OR p_type = 'ALL' OR e.event_type = p_type)
      AND (
          p_search IS NULL OR p_search = ''
          OR e.title ILIKE '%' || p_search || '%'
          OR e.description ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Calendar events retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_calendar_event_create(
    p_title TEXT,
    p_client_id UUID DEFAULT NULL,
    p_description TEXT DEFAULT NULL,
    p_event_type TEXT DEFAULT 'Meeting',
    p_start_time TIMESTAMPTZ DEFAULT now(),
    p_end_time TIMESTAMPTZ DEFAULT (now() + interval '1 hour')
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_event JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_calendar_event_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_calendar_event_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.calendar_events (
        title,
        client_id,
        description,
        event_type,
        start_time,
        end_time,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_title,
        p_client_id,
        p_description,
        p_event_type,
        p_start_time,
        p_end_time,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', e.id,
        'title', e.title,
        'description', e.description,
        'type', e.event_type,
        'startTime', e.start_time,
        'endTime', e.end_time,
        'date', to_char(e.start_time, 'YYYY-MM-DD'),
        'created_at', e.created_at
    ) INTO v_event
    FROM public.calendar_events e
    WHERE e.id = v_new_id;

    RETURN public.fn_response_success(v_event, NULL, 'Event created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_calendar_event_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_calendar_event_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_calendar_event_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.calendar_events
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Event deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- ENGAGEMENT RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_engagement_list(
    p_search TEXT DEFAULT NULL,
    p_platform TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_engagement_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_engagement_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', eg.id,
            'client_id', eg.client_id,
            'client', COALESCE(c.company, c.name, 'Client Account'),
            'platform', eg.platform,
            'date', eg.date,
            'likes', eg.likes,
            'comments', eg.comments,
            'shares', eg.shares,
            'reach', eg.reach,
            'impressions', eg.impressions,
            'performance', eg.performance,
            'notes', eg.notes,
            'tenant_id', eg.tenant_id,
            'created_at', eg.created_at
        ) ORDER BY eg.created_at DESC
    )
    INTO v_data
    FROM public.engagement eg
    LEFT JOIN public.clients c ON c.id = eg.client_id
    WHERE eg.tenant_id = v_tenant_id
      AND eg.is_active = true
      AND (p_platform IS NULL OR p_platform = 'ALL' OR eg.platform = p_platform)
      AND (
          p_search IS NULL OR p_search = ''
          OR eg.platform ILIKE '%' || p_search || '%'
          OR COALESCE(c.company, '') ILIKE '%' || p_search || '%'
      );

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Engagement data retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_engagement_create(
    p_client_id UUID DEFAULT NULL,
    p_platform TEXT DEFAULT 'LinkedIn',
    p_date TEXT DEFAULT CURRENT_DATE::text,
    p_likes INTEGER DEFAULT 0,
    p_comments INTEGER DEFAULT 0,
    p_shares INTEGER DEFAULT 0,
    p_reach INTEGER DEFAULT 0,
    p_impressions INTEGER DEFAULT 0,
    p_performance TEXT DEFAULT 'Strong',
    p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_entry JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_engagement_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_engagement_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.engagement (
        client_id,
        platform,
        date,
        likes,
        comments,
        shares,
        reach,
        impressions,
        performance,
        notes,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_client_id,
        p_platform,
        p_date,
        p_likes,
        p_comments,
        p_shares,
        p_reach,
        p_impressions,
        p_performance,
        p_notes,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', eg.id,
        'client_id', eg.client_id,
        'platform', eg.platform,
        'date', eg.date,
        'likes', eg.likes,
        'comments', eg.comments,
        'shares', eg.shares,
        'reach', eg.reach,
        'impressions', eg.impressions,
        'performance', eg.performance,
        'notes', eg.notes,
        'created_at', eg.created_at
    ) INTO v_entry
    FROM public.engagement eg
    WHERE eg.id = v_new_id;

    RETURN public.fn_response_success(v_entry, NULL, 'Engagement metric created successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_engagement_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_engagement_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_engagement_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.engagement
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Engagement record deleted successfully');
END;
$$;

-- ------------------------------------------------------------------------------
-- REPORTS RPC FUNCTIONS
-- ------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_report_list()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_data JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_report_list');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_report_list', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    SELECT jsonb_agg(
        jsonb_build_object(
            'id', r.id,
            'client_id', r.client_id,
            'client', COALESCE(c.company, c.name, 'Workspace Aggregate'),
            'week_start', r.week_start,
            'week_end', r.week_end,
            'report_data', r.report_data,
            'tenant_id', r.tenant_id,
            'created_at', r.created_at
        ) ORDER BY r.created_at DESC
    )
    INTO v_data
    FROM public.reports r
    LEFT JOIN public.clients c ON c.id = r.client_id
    WHERE r.tenant_id = v_tenant_id
      AND r.is_active = true;

    RETURN public.fn_response_success(COALESCE(v_data, '[]'::jsonb), NULL, 'Reports retrieved');
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_report_create(
    p_client_id UUID DEFAULT NULL,
    p_week_start DATE DEFAULT CURRENT_DATE,
    p_week_end DATE DEFAULT (CURRENT_DATE + 7),
    p_report_data JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
    v_profile_id INTEGER;
    v_new_id UUID;
    v_report JSONB;
BEGIN
    v_ctx := public.fn_get_request_context('fn_report_create');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_report_create', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;
    v_profile_id := (v_ctx->>'profile_id')::INTEGER;

    INSERT INTO public.reports (
        client_id,
        week_start,
        week_end,
        report_data,
        tenant_id,
        created_by,
        updated_by
    ) VALUES (
        p_client_id,
        p_week_start,
        p_week_end,
        p_report_data,
        v_tenant_id,
        v_profile_id,
        v_profile_id
    ) RETURNING id INTO v_new_id;

    SELECT jsonb_build_object(
        'id', r.id,
        'client_id', r.client_id,
        'week_start', r.week_start,
        'week_end', r.week_end,
        'report_data', r.report_data,
        'created_at', r.created_at
    ) INTO v_report
    FROM public.reports r
    WHERE r.id = v_new_id;

    RETURN public.fn_response_success(v_report, NULL, 'Report generated successfully', 201);
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_report_delete(
    p_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_ctx JSONB;
    v_tenant_id INTEGER;
BEGIN
    v_ctx := public.fn_get_request_context('fn_report_delete');
    IF NOT (v_ctx->>'is_authorized')::BOOLEAN THEN
        RETURN public.fn_response_error('fn_report_delete', 'UNAUTHORIZED', v_ctx->>'error_message', 403, NULL, NULL, v_ctx);
    END IF;

    v_tenant_id := (v_ctx->>'tenant_id')::INTEGER;

    UPDATE public.reports
    SET is_active = false, updated_at = now()
    WHERE id = p_id AND tenant_id = v_tenant_id;

    RETURN public.fn_response_success(jsonb_build_object('id', p_id), NULL, 'Report deleted successfully');
END;
$$;

-- ==============================================================================
-- PART 5: SEED DATA (DEFAULT TENANT, ROLES, SCOPES, PERMISSIONS, INITIAL PROFILES)
-- ==============================================================================

-- 1. Default Tenant
INSERT INTO public.tenants (id, name, slug, plan)
VALUES (1, 'Insight One Enterprise', 'insight-one-enterprise', 'Enterprise')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, plan = EXCLUDED.plan;

-- Reset sequence to avoid id conflict
SELECT setval(pg_get_serial_sequence('public.tenants', 'id'), (SELECT MAX(id) FROM public.tenants));

-- 2. Default Agency
INSERT INTO public.agencies (id, tenant_id, name, code, description)
VALUES (1, 1, 'Primary Agency', 'AG-01', 'Core operational agency for Insight One workspace')
ON CONFLICT DO NOTHING;

-- 3. Standard Roles
INSERT INTO public.roles (id, name, display_name, description)
VALUES
    (1, 'Admin', 'Workspace Administrator', 'Full administrative authority across all modules and tenant settings'),
    (2, 'Employee', 'Team Member', 'Standard staff member with operational access to projects, tasks, and clients')
ON CONFLICT (name) DO UPDATE SET display_name = EXCLUDED.display_name;

-- 4. Standard Scopes
INSERT INTO public.scopes (code, module, description)
VALUES
    ('*', 'system', 'Full system access'),
    ('client.read', 'clients', 'View client records'),
    ('client.create', 'clients', 'Create new client records'),
    ('client.update', 'clients', 'Update client information'),
    ('client.delete', 'clients', 'Remove client records'),
    ('project.read', 'projects', 'View projects'),
    ('project.create', 'projects', 'Create projects'),
    ('project.update', 'projects', 'Update projects'),
    ('project.delete', 'projects', 'Delete projects'),
    ('task.read', 'tasks', 'View tasks'),
    ('task.create', 'tasks', 'Create tasks'),
    ('task.update', 'tasks', 'Update tasks'),
    ('task.delete', 'tasks', 'Delete tasks'),
    ('team.read', 'team', 'View team directory'),
    ('team.create', 'team', 'Add team member'),
    ('team.update', 'team', 'Update member or credentials'),
    ('team.delete', 'team', 'Remove team member')
ON CONFLICT (code) DO NOTHING;

-- 5. Role Scopes (Admin has wildcard; Employee has operational scopes)
INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 1, s.id FROM public.scopes s WHERE s.code = '*'
ON CONFLICT DO NOTHING;

INSERT INTO public.role_scopes (role_id, scope_id)
SELECT 2, s.id FROM public.scopes s 
WHERE s.code IN ('client.read', 'project.read', 'task.read', 'task.update', 'team.read')
ON CONFLICT DO NOTHING;

-- 6. Role Menu Items (Database-driven navigation items)
-- Admin navigation
INSERT INTO public.role_menu_items (role_id, label, href, icon, display_order)
VALUES
    (1, 'Dashboard', '/dashboard', '▣', 1),
    (1, 'Team', '/team', '👥', 2),
    (1, 'Clients', '/clients', '◎', 3),
    (1, 'Projects', '/projects', '📁', 4),
    (1, 'Content', '/content', '✦', 5),
    (1, 'Tasks', '/tasks', '✓', 6),
    (1, 'Networking', '/networking', '◌', 7),
    (1, 'Engagement', '/engagement', '◔', 8),
    (1, 'Calendar', '/calendar', '◫', 9),
    (1, 'Statistics', '/statistics', '▤', 10),
    (1, 'Reports', '/reports', '▥', 11)
ON CONFLICT DO NOTHING;

-- Employee navigation
INSERT INTO public.role_menu_items (role_id, label, href, icon, display_order)
VALUES
    (2, 'Dashboard', '/dashboard', '▣', 1),
    (2, 'Clients', '/clients', '◎', 2),
    (2, 'Projects', '/projects', '📁', 3),
    (2, 'Content', '/content', '✦', 4),
    (2, 'Tasks', '/tasks', '✓', 5),
    (2, 'Calendar', '/calendar', '◫', 6),
    (2, 'Engagement', '/engagement', '◔', 7)
ON CONFLICT DO NOTHING;

-- 7. Seed Initial Profiles (Self-referencing created_by set to 1)
INSERT INTO public.profiles (
    id, user_id, email, full_name, role, department, phone, status, password, tenant_id, created_by
)
VALUES
    (1, '00000000-0000-0000-0000-000000000001'::uuid, 'admin@insightone.com', 'Admin User', 'Admin', 'Executive', '+1 (555) 019-2831', 'Active', 'Admin@123', 1, 1),
    (2, '00000000-0000-0000-0000-000000000002'::uuid, 'employee@insightone.com', 'Employee User', 'Employee', 'Content', '+1 (555) 014-9923', 'Active', 'Employee@123', 1, 1),
    (3, '00000000-0000-0000-0000-000000000003'::uuid, 'maya@insightone.ai', 'Maya Chen', 'Employee', 'Content', '+1 (555) 392-1049', 'Active', 'Maya@123', 1, 1),
    (4, '00000000-0000-0000-0000-000000000004'::uuid, 'alex@insightone.ai', 'Alex Rivera', 'Employee', 'Client Success', '+1 (555) 481-9920', 'Away', 'Alex@123', 1, 1)
ON CONFLICT (email) DO UPDATE SET 
    role = EXCLUDED.role,
    tenant_id = EXCLUDED.tenant_id;

-- Reset sequence on profiles
SELECT setval(pg_get_serial_sequence('public.profiles', 'id'), (SELECT MAX(id) FROM public.profiles));

-- ==============================================================================
-- PART 6: ROW LEVEL SECURITY & GRANT PERMISSIONS
-- ==============================================================================

-- Enable RLS across all tables
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.networking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_log ENABLE ROW LEVEL SECURITY;

-- Grant execution permissions on all RPC functions to authenticated & anon roles
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated;

-- Helper policies for direct reads while relying on RPC functions for mutations
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN
        SELECT unnest(ARRAY[
            'tenants', 'agencies', 'roles', 'scopes', 'role_scopes', 'role_menu_items',
            'profiles', 'clients', 'social_profiles', 'projects', 'content', 'tasks',
            'networking', 'engagement', 'calendar_events', 'reports', 'error_log'
        ])
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "policy_all_%s" ON public.%I;', tbl, tbl);
        EXECUTE format('CREATE POLICY "policy_all_%s" ON public.%I FOR ALL TO authenticated, anon USING (true) WITH CHECK (true);', tbl, tbl);
    END LOOP;
END $$;
