-- ==============================================================================
-- 01_core_multitenancy.sql
-- Insight One Core Multi-Tenancy, Profiles, RBAC & Error Logging Tables
-- ==============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tenants Table
CREATE TABLE IF NOT EXISTS public.tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    plan TEXT NOT NULL DEFAULT 'Enterprise',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL
);

-- 2. Agencies Table (One tenant can have multiple agencies)
CREATE TABLE IF NOT EXISTS public.agencies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    CONSTRAINT agencies_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 3. Roles Table (5 System Roles)
CREATE TABLE IF NOT EXISTS public.roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    description TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Scopes Table (Granular permissions mapped to functions & menus)
CREATE TABLE IF NOT EXISTS public.scopes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    module TEXT NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Role Scopes (RBAC join table)
CREATE TABLE IF NOT EXISTS public.role_scopes (
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    scope_id INTEGER NOT NULL REFERENCES public.scopes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, scope_id)
);

-- 6. Role Menu Items (Database-driven sidebar navigation)
CREATE TABLE IF NOT EXISTS public.role_menu_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    href TEXT NOT NULL,
    icon TEXT NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    required_scope TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 7. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    full_name TEXT NULL,
    phone TEXT NULL,
    avatar_url TEXT NULL,
    role TEXT NOT NULL DEFAULT 'Viewer',
    department TEXT NOT NULL DEFAULT 'General',
    status TEXT NOT NULL DEFAULT 'Active',
    password TEXT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NULL,
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    user_name TEXT NULL,
    tenant_id INTEGER NOT NULL,
    created_by INTEGER NOT NULL,
    updated_by INTEGER NULL,

    CONSTRAINT profiles_pkey1 PRIMARY KEY (id),
    CONSTRAINT profiles_email_unique UNIQUE (email),
    CONSTRAINT profiles_id_tenant_unique UNIQUE (id, tenant_id),
    CONSTRAINT profiles_user_id_unique UNIQUE (user_id),
    CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants (id),
    CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED
) TABLESPACE pg_default;

-- Link user_id to auth.users if auth schema is available
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'auth' AND table_name = 'users') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_name = 'profiles_user_id_fkey' AND table_name = 'profiles'
        ) THEN
            ALTER TABLE public.profiles 
            ADD CONSTRAINT profiles_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE;
        END IF;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- Add deferred foreign keys for agencies table referencing profiles
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'agencies_created_by_fkey' AND table_name = 'agencies'
    ) THEN
        ALTER TABLE public.agencies 
        ADD CONSTRAINT agencies_created_by_fkey 
        FOREIGN KEY (created_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'agencies_updated_by_fkey' AND table_name = 'agencies'
    ) THEN
        ALTER TABLE public.agencies 
        ADD CONSTRAINT agencies_updated_by_fkey 
        FOREIGN KEY (updated_by) REFERENCES public.profiles (id) DEFERRABLE INITIALLY DEFERRED;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- 8. Error Log Table (Captures sanitized internal errors)
CREATE TABLE IF NOT EXISTS public.error_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NULL,
    function_name TEXT NOT NULL,
    error_code TEXT NULL,
    error_message TEXT NULL,
    error_detail TEXT NULL,
    error_hint TEXT NULL,
    user_id UUID NULL,
    profile_id INTEGER NULL,
    metadata JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
