-- ==============================================================================
-- 02_business_tables.sql
-- Insight One Business Tables with Mandatory Multi-Tenancy Columns
-- Hierarchy: Tenants -> Agencies -> Clients -> Social Profiles
-- ==============================================================================

-- 1. Clients Table (Agency -> Clients)
CREATE TABLE IF NOT EXISTS public.clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id INTEGER NULL REFERENCES public.agencies(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NULL,
    website TEXT NULL,
    industry TEXT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    value TEXT DEFAULT '$25k',
    notes TEXT NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT clients_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 2. Social Profiles Table (Client -> Social Profiles)
CREATE TABLE IF NOT EXISTS public.social_profiles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    platform TEXT NOT NULL,
    handle TEXT NOT NULL,
    profile_url TEXT NULL,
    followers_count INTEGER NOT NULL DEFAULT 0,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT social_profiles_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 3. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NULL,
    project_manager TEXT NULL,
    assigned_team TEXT NULL,
    start_date DATE NULL,
    due_date DATE NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'Planning' CHECK (status IN ('Planning', 'In Progress', 'Review', 'Completed', 'On Hold')),
    progress INTEGER NOT NULL DEFAULT 0,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT projects_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 4. Content Pipeline Table
CREATE TABLE IF NOT EXISTS public.content (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    content_type TEXT NULL,
    platform TEXT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    due_date DATE NULL,
    stage TEXT NOT NULL DEFAULT 'idea' CHECK (stage IN (
        'idea',
        'topic_approval',
        'writing',
        'review',
        'design',
        'client_approval',
        'schedule',
        'publish'
    )),
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT content_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 5. Tasks Table
CREATE TABLE IF NOT EXISTS public.tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    assigned_employee TEXT NULL,
    priority TEXT NOT NULL DEFAULT 'Medium',
    status TEXT NOT NULL DEFAULT 'To Do' CHECK (status IN ('To Do', 'In Progress', 'Review', 'Done')),
    due_date DATE NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT tasks_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 6. Networking Table
CREATE TABLE IF NOT EXISTS public.networking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    person_name TEXT NOT NULL,
    company TEXT NOT NULL,
    email TEXT NULL,
    phone TEXT NULL,
    networking_type TEXT NOT NULL DEFAULT 'Call',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status TEXT NOT NULL DEFAULT 'Connected',
    notes TEXT NULL,
    follow_up_date DATE NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT networking_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 7. Engagement Table
CREATE TABLE IF NOT EXISTS public.engagement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    platform TEXT NOT NULL,
    date TEXT NOT NULL,
    likes INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    reach INTEGER NOT NULL DEFAULT 0,
    impressions INTEGER NOT NULL DEFAULT 0,
    performance TEXT DEFAULT 'Strong',
    notes TEXT NULL,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT engagement_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 8. Calendar Events Table
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    event_type TEXT NOT NULL DEFAULT 'Meeting',
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '1 hour'),
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT calendar_events_tenant_code_unique UNIQUE (tenant_id, code)
);

-- 9. Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NULL REFERENCES public.clients(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    week_start DATE NULL,
    week_end DATE NULL,
    report_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    
    -- Mandatory 11 multi-tenancy columns
    data JSONB NULL,
    metadata JSONB NULL,
    access_control JSONB NULL,
    tenant_id INTEGER NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by INTEGER NOT NULL REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by INTEGER NULL REFERENCES public.profiles(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT reports_tenant_code_unique UNIQUE (tenant_id, code)
);
